# These first two lines put us in the Trusty beta for Travis
# and keep us from using the container-based infrastructure.
sudo: required
dist: trusty

language: python
python:
  - 2.7

services:
  - docker
  - rabbitmq
  - postgresql

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

before_install:
  # Allow connections to PG from our Docker instance
  - echo "host all all 0.0.0.0/0 md5" | sudo tee -a /etc/postgresql/9.6/main/pg_hba.conf
  - echo "listen_addresses = '*'" | sudo tee -a /etc/postgresql/9.6/main/postgresql.conf
  - sudo service postgresql stop
  - sudo service postgresql start 9.6
  # Create Databases
  - psql -U postgres -h 127.0.0.1 -c "CREATE USER exchange WITH SUPERUSER PASSWORD 'boundless'"
  - psql -U postgres -h 127.0.0.1 -c "CREATE DATABASE exchange WITH OWNER exchange"
  - psql -U postgres -h 127.0.0.1 -c "CREATE DATABASE exchange_data WITH OWNER exchange"
  - psql -U postgres -h 127.0.0.1 -d exchange_data -c "CREATE EXTENSION postgis"

install:
  # Setup and Start Django Container
  - docker build -t django -f docker/travis/Dockerfile.django .
  - docker run -d -p 8000:8000 --name django django
  # Install chromedriver
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin

before_script:
  # setup local pytest env
  - pip install Pillow python-resize-image Django==1.8.17
  - pip install selenium flake8 pytest coverage pytest-cov
  - export DJANGO_SETTINGS_MODULE='exchange.settings'
  - export PYTEST=1
  - PYTEST=True bash -c 'python manage.py migrate'
  - PYTEST=True bash -c 'python manage.py collectstatic --noinput'
  # Start XVFB for running tests
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3 # give xvfb some time to start

script:
  # Basic test if Django is up
  - wget http://localhost:8000
  # flake8 tests
  - python -m flake8 --ignore=F405,F403 --statistics /opt/boundless/exchange/exchange
  # run pytests
  - PYTEST=True bash -c 'py.test --cov exchange exchange/tests/ --cov-report term-missing'

after_success:
  - coveralls

after_failure:
- docker logs django

#notifications:
#  slack:
#    secure: Z2nAgjWI9sLH874otcCaxiTYz0Emsco1hbqi6H4dVJo+kREHuq9jjiGzIIs6+1fi3QzUxxoWgL7mddB/ngkOCwfMimm8tnD5xbYjdr/zNVChQTS8l25ZjsoMi0pDdwAFwQ6sKpFAAZY5Hsl9KGXxjfwbeYNnJL4QKGVBOmSZ8sdtRVulyLdrVM1C3mrYF9yyR/Yr3/F6/IrSuDDOBVS+6jrl5P9PCQvmQWkqMFBIevY0NS0111Oi6qzSUladK27juBmZXOFQpJqJ1gTcCbuQkj/57SXuYH1KbuTxK5w+ghjuyJKpN4EYNvnjEjpgSVgvYaiIX3FgDhK6YaptFA3/siQgSKq1GTbC6gsY3toZlKxfDlqRDS3K1oSPXIiWuJrWV7JH49GaORtqq2FaFCn3D/Fwdc4WH6OveaFYiC/hpXI6M0gqLwTY9LqpNbEqMvHCI3RcBtY/jkhu3ErGKdB5waYuvyD5QfRVvBoY0411iu2k16SqWcBzaS9fZhh25rKQ449iPrTwlGdjV1jjpSBDoMRgOFulCTHhQKHO7QqJzE1TTeydYzFb1MDotBHt4MZz29D6/68KJfLV+7Tr83DwyX7I+Oeb2hUCcDT9xfYZoCmZAjrow0mYLrqWv087BGzvygny9b5pIu4ia05UrralZeoUlMovvZBzMogF3kWYikQ=
